# ----------------------------------------------------------------------
# Copyright© 2024-2025 China Mobile (SuZhou) Software Technology Co.,Ltd.
#
# qcos is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions
# of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# ----------------------------------------------------------------------

version: '3'
services:
  prefect-server:
    container_name: prefect-server
    image: ${REGISTRY}${PREFECT_IMAGE_NAME}:${PREFECT_IMAGE_VERSION}
    restart: always
    command: /bin/sh -c 'rm -rf /var/qcos/db/prefect.db-shm /var/qcos/db/prefect.db-wal; prefect server start --host ""'
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
      PREFECT_SERVER_API_HOST: ${PREFECT_SERVER_API_HOST}
      PREFECT_SERVER_DATABASE_CONNECTION_URL: ${PREFECT_SERVER_DATABASE_CONNECTION_URL}
      PREFECT_API_DATABASE_TIMEOUT: 30
      PREFECT_API_URL: "${PREFECT_API_URL}"
      PREFECT_LOCAL_STORAGE_PATH: /var/qcos/storage
      PREFECT_API_DEFAULT_LIMIT: 100000
      PYTHONPATH: /root/qcos-project/src
    volumes:
      - /etc/hosts:/etc/hosts
      - /var/log/qcos:/var/log/qcos
      - /var/qcos:/var/qcos
      - /etc/qcos/prefect:/root/.prefect
  redis:
    image: ${REGISTRY}${REDIS_IMAGE_NAME}:${REDIS_IMAGE_VERSION}
    container_name: redis
    restart: always
    network_mode: "host"
  qcos-dev:
    container_name: qcos-dev
    image: ${REGISTRY}${QCOS_REGISTRY}${QCOS_IMAGE_NAME}:${QCOS_IMAGE_VERSION}
    privileged: true
    network_mode: "host"
    restart: always
    stdin_open: True
    tty: True
    depends_on:
      - prefect-server
      - redis
    working_dir: /root/qcos-project
    environment:
      DEBUG: ${DEBUG}
      DEV: ${DEV}
      TZ: Asia/Shanghai
      CONTAINER_NAME: ${QCOS_CONTAINER_NAME}
      API_SERVER_LISTEN_IP: ${API_SERVER_LISTEN_IP}
      API_SERVER_LISTEN_PORT: ${API_SERVER_LISTEN_PORT}
      QCOS_SERVER_IP: ${QCOS_SERVER_IP}
      QCOS_SERVER_PORT: ${QCOS_SERVER_PORT}
      QCOS_ENABLE_VIRT: ${QCOS_ENABLE_VIRT}
      QCOS_VIRTUAL_INSTANCE_ID: ${QCOS_VIRTUAL_INSTANCE_ID}
      LOCAL_CICD: ${LOCAL_CICD}
      PREFECT_API_URL: ${PREFECT_API_URL}
      PREFECT_SERVER_DATABASE_CONNECTION_URL: ${PREFECT_SERVER_DATABASE_CONNECTION_URL}
      PREFECT_LOCAL_STORAGE_PATH: ${PREFECT_LOCAL_STORAGE_PATH}
      REDIS_SERVER_IP: ${REDIS_SERVER_IP}
      REDIS_SERVER_PORT: ${REDIS_SERVER_PORT}
      PYTHONPATH: /root/qcos-project/src
    command: "-w http://${PREFECT_SERVER_API_HOST:-127.0.0.1}:${PREFECT_SERVER_PORT}/api"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - /etc/hosts:/etc/hosts
      - /etc/qcos:/etc/qcos
      - /var/log/qcos:/var/log/qcos
      - /var/run/qcos:/var/run/qcos
      - ${QCOS_LOCAL_SRC_DIR}:/root/qcos-project
      - ${QCOS_LOCAL_SRC_DIR}/bin/qcos-cli.py:/usr/bin/qcos-cli
    entrypoint: /entrypoint.sh
