# ----------------------------------------------------------------------
# Copyright© 2024-2025 China Mobile (SuZhou) Software Technology Co.,Ltd.
#
# qcos is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions
# of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# ----------------------------------------------------------------------

version: '3'
services:
  qcos-cli:
    container_name: qcos-cli
    image: ${REGISTRY}${QCOS_REGISTRY}${QCOS_IMAGE_NAME}-cli:${QCOS_IMAGE_VERSION}
    network_mode: "host"
    restart: always
    stdin_open: True
    tty: True
    working_dir: /root
    environment:
      TZ: Asia/Shanghai
      CONTAINER_NAME: ${QCOS_CONTAINER_NAME}
      QCOS_SERVER_IP: ${QCOS_SERVER_IP}
      QCOS_SERVER_PORT: ${QCOS_SERVER_PORT}
      QCOS_VIRTUAL_INSTANCE_ID: ${QCOS_VIRTUAL_INSTANCE_ID}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - /etc/hosts:/etc/hosts
    entrypoint: /entrypoint.sh
